2025-09-17 21:07:43,640 [INFO] worker: ENGINE selected: patchright
2025-09-17 21:07:43,735 [ERROR] worker: resolve_timezone_via_proxy failed
Traceback (most recent call last):
  File "D:\SOFTS\AntiServer\worker.py", line 72, in run_worker
    tz = await resolve_timezone_via_proxy(server, creds)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SOFTS\AntiServer\utils.py", line 62, in resolve_timezone_via_proxy
    async with httpx.AsyncClient(proxies=proxy_url, timeout=timeout, verify=False) as client:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AsyncClient.__init__() got an unexpected keyword argument 'proxies'
